# -*- coding: utf-8 -*-
"""Retail_Inventory_Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/173mMsfLMbRsT4CgORvDEn1w_n6TD2xGv
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_excel(list(uploaded.keys())[0])

df.head()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('ggplot')

print(df.shape)

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

df = df.drop_duplicates()

num_cols = df.select_dtypes(include=np.number).columns

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

df = df.fillna("Unknown")

df[['Opening Stock','Units Sold','Reorder Point']].describe()
df = df[df['Opening Stock'] >= 0]
df = df[df['Units Sold'] >= 0]
df = df[df['Reorder Point'] >= 0]

category_count = df['Category'].value_counts()

print(category_count)

category_sales = df.groupby('Category')['Units Sold'].sum()

print(category_sales.sort_values(ascending=False))

top_products = df.nlargest(10,'Units Sold')

top_products[['Product Name','Units Sold']]

low_stock = df.nsmallest(10,'Opening Stock')

low_stock[['Product Name','Opening Stock']]

reorder_products = df[
    df['Opening Stock'] <= df['Reorder Point']
]

reorder_products

supplier_products = df.groupby('Supplier Name').size()
print(supplier_products)

plt.figure(figsize=(10,6))

category_sales.sort_values().plot(kind='bar')

plt.title("Category-wise Units Sold")
plt.xlabel("Category")
plt.ylabel("Units Sold")

plt.show()

plt.figure(figsize=(8,8))

category_count.plot(
    kind='pie',
    autopct='%1.1f%%'
)

plt.ylabel('')
plt.title("Category Distribution")

plt.show()

plt.figure(figsize=(8,5))

plt.hist(df['Opening Stock'], bins=20)

plt.title("Stock Distribution")
plt.xlabel("Stock")
plt.ylabel("Frequency")

plt.show()

df_sorted = df.sort_values('Units Sold')

plt.figure(figsize=(12,6))

plt.plot(df_sorted['Units Sold'].values,
         label='Units Sold')

plt.plot(df_sorted['Closing Stock'].values,
         label='Closing Stock')

plt.legend()

plt.title("Stock vs Sales")

plt.show()

plt.figure(figsize=(8,6))

sns.heatmap(
    df.corr(numeric_only=True),
    annot=True,
    cmap='coolwarm'
)

plt.title("Correlation Heatmap")

plt.show()